In [9]:
import numpy as np
import pandas as pd
from scipy.stats import multivariate_normal
from matplotlib import pyplot as plt
from sklearn.datasets import make_classification
from sklearn.preprocessing import MinMaxScaler
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.utils.estimator_checks import check_estimator
from sklearn.utils.validation import check_X_y, check_array, check_is_fitted
from sklearn.utils.multiclass import unique_labels
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from mlxtend.plotting import plot_decision_regions
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.utils.estimator_checks import check_estimator
from sklearn.utils.validation import check_X_y, check_array, check_is_fitted
from sklearn.utils.multiclass import unique_labels
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
from sklearn.metrics import accuracy_score, mean_squared_error
from sklearn.feature_extraction.text import CountVectorizer, ENGLISH_STOP_WORDS
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
import re

In [26]:
#dataset import
df = pd.read_csv("original_set.csv")

In [28]:
print(df)

         pl_name hostname  default_flag  sy_snum  sy_pnum  discoverymethod  \
0       11 Com b   11 Com             1        2        1  Radial Velocity
1       11 Com b   11 Com             0        2        1  Radial Velocity
2       11 UMi b   11 UMi             0        1        1  Radial Velocity
3       11 UMi b   11 UMi             1        1        1  Radial Velocity
4       11 UMi b   11 UMi             0        1        1  Radial Velocity
...          ...      ...           ...      ...      ...              ...
32111  ups And d  ups And             0        2        3  Radial Velocity
32112  ups And d  ups And             0        2        3  Radial Velocity
32113  ups Leo b  ups Leo             1        1        1  Radial Velocity
32114   xi Aql b   xi Aql             0        1        1  Radial Velocity
32115   xi Aql b   xi Aql             1        1        1  Radial Velocity

       disc_year                           disc_facility              soltype  \
0           2007                        Xinglong Station  Published Confirmed
1           2007                        Xinglong Station  Published Confirmed
2           2009  Thueringer Landessternwarte Tautenburg  Published Confirmed
3           2009  Thueringer Landessternwarte Tautenburg  Published Confirmed
4           2009  Thueringer Landessternwarte Tautenburg  Published Confirmed
...          ...                                     ...                  ...
32111       1999                  Multiple Observatories  Published Confirmed
32112       1999                  Multiple Observatories  Published Confirmed
32113       2021       Okayama Astrophysical Observatory  Published Confirmed
32114       2007       Okayama Astrophysical Observatory  Published Confirmed
32115       2007       Okayama Astrophysical Observatory  Published Confirmed

       pl_controv_flag  ... sy_vmagerr2  sy_kmag  sy_kmagerr1  sy_kmagerr2  \
0                    0  ...      -0.023    2.282        0.346       -0.346
1                    0  ...      -0.023    2.282        0.346       -0.346
2                    0  ...      -0.005    1.939        0.270       -0.270
3                    0  ...      -0.005    1.939        0.270       -0.270
4                    0  ...      -0.005    1.939        0.270       -0.270
...                ...  ...         ...      ...          ...          ...
32111                0  ...      -0.023    2.859        0.274       -0.274
32112                0  ...      -0.023    2.859        0.274       -0.274
32113                0  ...      -0.023    2.184        0.248       -0.248
32114                0  ...      -0.023    2.171        0.220       -0.220
32115                0  ...      -0.023    2.171        0.220       -0.220

       sy_gaiamag  sy_gaiamagerr1  sy_gaiamagerr2  rowupdate  pl_pubdate  \
0         4.44038        0.003848       -0.003848  2014/5/14      Jan-08
1         4.44038        0.003848       -0.003848  2014/7/23      Aug-11
2         4.56216        0.003903       -0.003903  2018/4/25      Aug-11
3         4.56216        0.003903       -0.003903   2018/9/4      Mar-17
4         4.56216        0.003903       -0.003903  2018/4/25      Oct-09
...           ...             ...             ...        ...         ...
32111     3.98687        0.008937       -0.008937  2021/9/20      May-21
32112     3.98687        0.008937       -0.008937   2021/8/3      Jun-10
32113     4.03040        0.008513       -0.008513  2022/1/10      Dec-21
32114     4.42501        0.003837       -0.003837  2014/7/23      Aug-11
32115     4.42501        0.003837       -0.003837  2014/5/14      Jun-08

       releasedate
0        2014/5/14
1        2014/7/23
2        2014/7/23
3         2018/9/6
4        2014/5/14
...            ...
32111    2021/9/20
32112     2021/8/3
32113    2022/1/10
32114    2014/7/23
32115    2014/5/14

[32116 rows x 92 columns]

In [44]:
df_comp = df[["pl_bmasse","pl_rade"]]
df_comp = df_comp.dropna()
df_comp.head()

     pl_bmasse  pl_rade
26    2543.000   18.647
34    4417.837   16.141
39    6657.480   10.310
97       8.080    1.920
101      7.810    2.080

In [51]:
pd.set_option('display.max_rows',None)
df.isna().sum()

pl_name                0
hostname               0
default_flag           0
sy_snum                0
sy_pnum                0
discoverymethod        0
disc_year              0
disc_facility          0
soltype                0
pl_controv_flag        0
pl_refname             0
pl_orbper           2798
pl_orbpererr1       4021
pl_orbpererr2       4022
pl_orbperlim        2793
pl_orbsmax         14008
pl_orbsmaxerr1     28006
pl_orbsmaxerr2     28007
pl_orbsmaxlim      11301
pl_rade             9613
pl_radeerr1        10230
pl_radeerr2        10230
pl_radelim          6940
pl_radj            22638
pl_radjerr1        23210
pl_radjerr2        23210
pl_radjlim         22638
pl_bmasse          27494
pl_bmasseerr1      27926
pl_bmasseerr2      27926
pl_bmasselim       27494
pl_bmassj          27495
pl_bmassjerr1      27932
pl_bmassjerr2      27932
pl_bmassjlim       27495
pl_bmassprov       27494
pl_orbeccen        15528
pl_orbeccenerr1    29583
pl_orbeccenerr2    29584
pl_orbeccenlim     12854
pl_insol           18427
pl_insolerr1       18629
pl_insolerr2       18629
pl_insollim        13663
pl_eqt             17421
pl_eqterr1         30639
pl_eqterr2         30639
pl_eqtlim          14928
ttv_flag               0
st_refname             0
st_spectype        30393
st_teff             1817
st_tefferr1         2353
st_tefferr2         2589
st_tefflim          1817
st_rad              1702
st_raderr1          7030
st_raderr2          7167
st_radlim           1702
st_mass             4297
st_masserr1         9620
st_masserr2         9757
st_masslim          4297
st_met             11282
st_meterr1         11900
st_meterr2         11900
st_metlim           9006
st_metratio        11544
st_logg             5314
st_loggerr1        10290
st_loggerr2        10291
st_logglim          5314
sy_refname             0
rastr                  0
ra                     0
decstr                 0
dec                    0
sy_dist              787
sy_disterr1         1588
sy_disterr2         1588
sy_vmag              370
sy_vmagerr1          383
sy_vmagerr2          384
sy_kmag              388
sy_kmagerr1          596
sy_kmagerr2          596
sy_gaiamag           658
sy_gaiamagerr1       658
sy_gaiamagerr2       658
rowupdate              1
pl_pubdate             0
releasedate            0
dtype: int64